language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: SLqS1KLJL7isZE5DBPUDiPCkJV+bsWk9LjhqlE5j7xgfJSM4SvPRBGBTqteFdrVscd//bbCBjOXWClQKjzeD8uJqDmCLcxT+ASPky2lFL7A77xYU7ltQ/AD9p9mN1EITb8JnNrOXkBx2vnKGsAJL0mrW1N57S0wvSHv4ysE6R86Zd14TKZcAzCe+a23+frqNxM57rErp43b1/alYNQGwu3rWjeCkuibYeq1cxab+og20Gj/i0tL82EtSilXXX1vr5ZD9WEpiNV8IF7jcvmbXgGjkHe93+cfg5kOHPRsbAo8hF2F5I8DGxDZXOaZje66E6qizAUvoqAbeJwzm8OV0NtoU3es2882g6KHmmJJ6F6/2/v/2En1FvBAEmaR7wSUulp2onUGG0SasJz+w27zDKolxhIpRKh68xFFVie7hq8Mlq57Hd8Sq0f+XO2n5xMQxgOeIYeGKOozmRiF4D69PR5yp8XCM3I4Q3Ta1A6QlT2443PIC9p875JNHZaYKCA0xKbMwwvoS4F2WHJbvEj08Nc/HHN5fTx2KJK8vgsIYmCBDAlKBZTEEKO5qkiOKIOqR0/lGTOd3X8FkbX60iNsJBf+NdqBuCB3CF+oBqpgNTf7TgSUj6jrR2TfkvGC0PYpugnGjCa+Nozei79j5mAapcHSM8QNBsKENDb9qY/uWdsI=
  - secure: LiQZTsXmZt1Hp/7TbSw7nZLrwAIAFREKvPLGJFMSQpoznBDEUmCHt0XWOA0TckFRSbDZvL8TX9wtlFv8iS88VKhgcyGQ6nMn2L+tLep6NK/IWexkfQzMGhFXw56kqX5+6JVMLHdclSA9lH1YHcLH3Mzo2Rvru26QEubFT8stU0GpV0voJ2BJ0uz7u16yvDjg7RMu3/Hk2bnzHdoVqgwcMf3tM3OEK+q810DtHyI/7I2eQfZFExr5P3U7WGCp5BLygD1hXs3eRT//3NJyxddAP/7ReA8rLjdBd9BQc5gM3djkfORc4KYTcuiTtwPu0g19lMkoKQPNf9KXZiO69833w5pUhwWNf5S8MnMzNqMcY1fB6h3zakqM7LfCA87bh43mRc07SNf4tSl5mTuc8VYBqdTWfASID50XrdyYWf+vUThcXWYDHYZ0ziES8uykvORq2L3zOkH6Z1G7zzALC8b/UWQyrZP+PC7CfKWx/eQ5/7teJvcxeEtoWiRj0VeD6RL6jBZaqOBCn9Bxmihfp4Wx6S5SZZnDX24l5tp8jIDRP8nBalqr9pukjC0bjpkYSdKUBMJK2Q5BBLMy08ANU4L31X7ZfP/exc20LkstTM1Yts3y5jVZLLRioIgpxDOxvaNk2FvedO82JqiYoEJVIDc7iQppMmkkT3SsE/V5AAoXotw=
install: "./gradlew assemble -PbintrayUser=${bintrayUser} -PbintrayKey=${bintrayKey}"
script: "./gradlew clean build :sirocco-core:bintrayUpload -x fregeQuickCheck -PbintrayUser=${bintrayUser}
  -PbintrayKey=${bintrayKey}"
branches:
  only:
  - master
