language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: h/5xX1pPWw7S1VDagy6s5lHY/4LAn7n/yM8nLN71W5f8vseJessouDXKVpCPZjiN+UuHrIl+vkhLFBuT6OjOaUno6JiIRJ+tmVhtYD3gOVH2QjvWYUvfT+wj+C+pno2UqLYz9xe6hW6BxA47hj5a5vShs6XiddbWNtYecc/yQK5g+Kiy78K/KK7MbQ3sw/DEE/Tsb1XY/ZlEUpbwv9lKdtIayLPH2Zh6wycclZNqjwNdJUh5fHMjZBNhu2Ve6webPFB3qD5BrJT4rC6PowgYvLQ2+RJg9g84/ZW6YIJ/D/zmh0HIeJ53OVFansx3b1jE2T5WUuByzHCeqTWqVSvV/cWztAgCiI3VhghUqDUapc0UEpwvuY80d4/y+8g7ZUJ7Rjz9o1IzLpwonRRcUO25b5VyKVCh8Zr9BTvSkAeZ84g3svLy7NNT+MsNN7r0tBNX9Fi1FySC/ZJsK3d+scCp2KSbmhS80HA0wvaGanoWecSCJ67dEuvS3MPQqPv8K1qF4SqXcaho1LZ4wqo/a67FMvlDLSARi8AiS+m/M/YzynuZEw+l6Z6LmWcEMCOJ/u1sq5jJuDdFdubi70RAZ7Sr4caNkOa/kmRyMHmI+XxDapp3Oo1rDEgA+Kx8ad41ySwFdBVMxQiI7KFl3Y/WXuGX7md4ru46zIYJS6hNbzXDvYw=
  - secure: WyrfZ81Nmo5zhk2tNg94HmUSw+Q7nQ3BnhSegSViwdnuNt5zzi7bKFEuZVnKqe4588jL+U38UkJpgaQ6G95aSDSIA9W/jPMN0A50XPKpXsYZAUCBMfcribQMEUZW9O2kE4YOVDg83q1DnNhQFYGhfTFvL+Nof7mbYRlKWXFNiBW0Vi9NvfgrJ16GMOLfH8DmR04PrR7ARxXs7Wh+zLW1mxkFvu1OmZ6kwqlC5WLP+HXD3RcPpTydwF8UWuM68uWkhuRm58mEeP/C8a40/77h+GeQUafgIBv2n365FNp+ykYHYrpe/r0DzsAkeKXJg20xV+4TVG/vtTdwhl7AlCvivHSeniuTW62JibwwmhGGeDyi0IwzTgyE4YqZBoDIrc0jibJQnT/KSnkWoGiyimQkcHD6iY5NO8yvTDcgC1/d+sdSWgEJd6BgHvCY//2XIYdFist65S/30gB7VYkQhGg07faBDTcGTaS+KDwcePv2phdcRJNvCtiFll87IwrkfdQilQrg202VgRi6fR73kdYhersLhup8MvgMSkIGvCo8w2NPip9B87VFskemid031Wyw8fjk5tp3nRhQDPdEv6DTQAAdvvoQapnkh49fxPx2+b9VK3QPhv8997B/iuZw/FveZcqz6fSmpQMFHLSfybWbEZcOiPOJei6keaxO/pI9050=
install: "./gradlew assemble -PbintrayUser=${bintrayUser} -PbintrayKey=${bintrayKey}"
script: "./gradlew clean build :sirocco-core:bintrayUpload -x fregeQuickCheck -PbintrayUser=${bintrayUser}
  -PbintrayKey=${bintrayKey}"
branches:
  only:
  - master
